# Generated by Django 6.0.7 on 2026-09-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='daily_study_hours',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
