# Generated by Django 6.0.7 on 2026-08-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roadmapphase',
            old_name='week_number',
            new_name='end_week',
        ),
        migrations.AddField(
            model_name='roadmapphase',
            name='milestone',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='roadmapphase',
            name='phase_objective',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='roadmapphase',
            name='start_week',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
