# Generated by Django 6.0.7 on 2026-08-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='topicquiz',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='topicresource',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='topic',
            name='estimated_hours',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='topicresource',
            name='resource_type',
            field=models.CharField(choices=[('Video', 'Video'), ('Article', 'Article'), ('Documentation', 'Documentation'), ('Practice', 'Practice')], default='Article', max_length=30),
        ),
    ]
