# Generated by Django 6.0.7 on 2026-09-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_scheduled_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyprogress',
            options={'ordering': ['-study_date', '-created_at']},
        ),
        migrations.AlterField(
            model_name='dailyprogress',
            name='time_spent',
            field=models.PositiveIntegerField(help_text='Study time in minutes'),
        ),
    ]
